export const PAGE_STYLES = {
  login: {
    container: "min-h-[80vh] flex items-center justify-center",
    subContainer: "flex items-center gap-8 w-full max-w-4xl px-4",
    imgBlock: "hidden md:block flex-1",
    cardBlock: "flex-1 w-full",
    form : "flex flex-col gap-3",
    formError: "alert alert-error text-sm",
    formInput: "input input-bordered w-full px-4",
    formAccount: "text-center mt-3",
    formAccountLink: "link link-hover",
  },

  signup: {
    container: "container mx-auto max-w-4xl p-5",
    subContainer: "flex items-center gap-8",
    imgBlock: "hidden md:block flex-1",
    cardBlock: "flex-1 w-full",
    cardHeading: "text-3xl font-bold mb-5",
    form: "flex flex-col gap-3",
    formInput: "input input-bordered w-full px-4",
    formAccount: "text-center mt-3",
    formAccountLink: "link link-hover",
    toastContainer: "toast toast-end toast-bottom m-4",
    toastAlert: "alert px-6 py-4 min-w-[300px] shadow-lg",
    toastSuccess: "alert-success",
    toastError: "alert-error",
    toastInfo: "alert-info",
    toastMessage: "text-base",
  },

  forgotPassword: {
    container: "min-h-[80vh] flex items-center justify-center",
    subContainer: "flex items-center gap-8 w-full max-w-4xl px-4",
    imgBlock: "hidden md:block flex-1",
    cardBlock: "flex-1 w-full",
    form: "flex flex-col gap-3",
    formError: "alert alert-error text-sm",
    formInput: "input input-bordered w-full px-4",
    formAccount: "text-center mt-3",
    formAccountLink: "link link-hover",
  },

  otpVerify: {
    container: "min-h-[80vh] flex items-center justify-center",
    subContainer: "flex items-center gap-8 w-full max-w-4xl px-4",
    imgBlock: "hidden md:block flex-1",
    cardBlock: "flex-1 w-full",
    form: "flex flex-col gap-4",
    formError: "alert alert-error text-sm",
    otpContainer: "flex justify-center gap-2",
    otpInput: "input input-bordered w-12 h-12 text-center text-xl font-bold",
    formAccount: "text-center mt-3",
    formAccountLink: "link link-hover",
  },

  resetPassword: {
    container: "min-h-[80vh] flex items-center justify-center",
    subContainer: "flex items-center gap-8 w-full max-w-4xl px-4",
    imgBlock: "hidden md:block flex-1",
    cardBlock: "flex-1 w-full",
    form: "flex flex-col gap-3",
    formError: "alert alert-error text-sm",
    formInput: "input input-bordered w-full px-4",
    formAccount: "text-center mt-3",
    formAccountLink: "link link-hover",
    toastContainer: "toast toast-end toast-bottom m-4",
    toastAlert: "alert px-6 py-4 min-w-[300px] shadow-lg",
  },

  cart: {
    container: "p-3 md:p-5",
    heading: "text-xl md:text-2xl font-bold",
    mobileCardLayout: "flex flex-col gap-4 mt-4 md:hidden",
    mobileCard: "rounded-lg p-4 flex flex-col gap-3",
    mobileCardImage: "w-16 h-16 object-cover rounded",
    mobileTitle: "text-sm font-semibold truncate",
    mobilePrice: "text-lg font-bold text-orange-500",
    mobileQuantityControls: "flex items-center gap-3",
    mobileQuantityIncrementButton: "btn btn-outline-secondary btn-sm",
    mobileQuantityDecrementButton: "btn btn-outline-secondary btn-sm",
    desktopTableLayout: "hidden md:block overflow-x-auto mt-4",
    desktopTable: "table table-striped",
    cartItemTotal: "mt-5 text-right"
  }
};